package com.msr.oms.entity;
// Generated Jul 11, 2019 5:20:20 PM by Hibernate Tools 5.1.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CurrencyMaster generated by hbm2java.
 */
@Entity
@Table(name = "currency_master")
public class CurrencyMaster implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 5515200013058122158L;
	
	/** The currency id. */
	private Long currencyId;
	
	/** The currency code. */
	private String currencyCode;
	
	/** The currency name. */
	private String currencyName;
	
	/** The status. */
	private boolean status;
	
	/** The created on. */
	private Date createdOn;
	
	/** The created by. */
	private String createdBy;
	
	/** The orderses. */
	private Set<Orders> orderses = new HashSet<Orders>(0);

	/**
	 * Gets the currency id.
	 *
	 * @return the currency id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "currency_id", unique = true, nullable = false)
	public Long getCurrencyId() {
		return this.currencyId;
	}

	/**
	 * Sets the currency id.
	 *
	 * @param currencyId the new currency id
	 */
	public void setCurrencyId(Long currencyId) {
		this.currencyId = currencyId;
	}

	/**
	 * Gets the currency code.
	 *
	 * @return the currency code
	 */
	@Column(name = "currency_code", nullable = false, length = 50)
	public String getCurrencyCode() {
		return this.currencyCode;
	}

	/**
	 * Sets the currency code.
	 *
	 * @param currencyCode the new currency code
	 */
	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}

	/**
	 * Gets the currency name.
	 *
	 * @return the currency name
	 */
	@Column(name = "currency_name", nullable = false, length = 100)
	public String getCurrencyName() {
		return this.currencyName;
	}

	/**
	 * Sets the currency name.
	 *
	 * @param currencyName the new currency name
	 */
	public void setCurrencyName(String currencyName) {
		this.currencyName = currencyName;
	}

	/**
	 * Checks if is status.
	 *
	 * @return true, if is status
	 */
	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	/**
	 * Sets the status.
	 *
	 * @param status the new status
	 */
	public void setStatus(boolean status) {
		this.status = status;
	}

	/**
	 * Gets the created on.
	 *
	 * @return the created on
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	/**
	 * Sets the created on.
	 *
	 * @param createdOn the new created on
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	/**
	 * Gets the created by.
	 *
	 * @return the created by
	 */
	@Column(name = "created_by", nullable = false, length = 80)
	public String getCreatedBy() {
		return this.createdBy;
	}

	/**
	 * Sets the created by.
	 *
	 * @param createdBy the new created by
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * Gets the orderses.
	 *
	 * @return the orderses
	 */
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "currencyMaster")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	/**
	 * Sets the orderses.
	 *
	 * @param orderses the new orderses
	 */
	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
