package com.msr.oms.entity;
// Generated Jul 11, 2019 5:20:20 PM by Hibernate Tools 5.1.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerAddress generated by hbm2java.
 */
@Entity
@Table(name = "customer_address")
public class CustomerAddress implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = -5788476740656012901L;
	
	/** The customer address id. */
	private Long customerAddressId;
	
	/** The country master. */
	private CountryMaster countryMaster;
	
	/** The customer. */
	private Customer customer;
	
	/** The customer address type master. */
	private Long customerAddressTypeId;
	
	/** The status. */
	private boolean status;
	
	/** The streat address. */
	private String streatAddress;
	
	/** The streat address 2. */
	private String streatAddress2;
	
	/** The suburb. */
	private String suburb;
	
	/** The city. */
	private String city;
	
	/** The state. */
	private String state;
	
	/** The created on. */
	private Date createdOn;
	
	/** The created by. */
	private String createdBy;

	/**
	 * Gets the customer address id.
	 *
	 * @return the customer address id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "customer_address_id", unique = true, nullable = false)
	public Long getCustomerAddressId() {
		return this.customerAddressId;
	}

	/**
	 * Sets the customer address id.
	 *
	 * @param customerAddressId the new customer address id
	 */
	public void setCustomerAddressId(Long customerAddressId) {
		this.customerAddressId = customerAddressId;
	}

	/**
	 * Gets the country master.
	 *
	 * @return the country master
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "country_id", nullable = false)
	public CountryMaster getCountryMaster() {
		return this.countryMaster;
	}

	/**
	 * Sets the country master.
	 *
	 * @param countryMaster the new country master
	 */
	public void setCountryMaster(CountryMaster countryMaster) {
		this.countryMaster = countryMaster;
	}

	/**
	 * Gets the customer.
	 *
	 * @return the customer
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	/**
	 * Sets the customer.
	 *
	 * @param customer the new customer
	 */
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	/**
	 * Checks if is status.
	 *
	 * @return true, if is status
	 */
	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	/**
	 * Sets the status.
	 *
	 * @param status the new status
	 */
	public void setStatus(boolean status) {
		this.status = status;
	}

	/**
	 * Gets the streat address.
	 *
	 * @return the streat address
	 */
	@Column(name = "streat_address", nullable = false, length = 100)
	public String getStreatAddress() {
		return this.streatAddress;
	}

	/**
	 * Sets the streat address.
	 *
	 * @param streatAddress the new streat address
	 */
	public void setStreatAddress(String streatAddress) {
		this.streatAddress = streatAddress;
	}

	/**
	 * Gets the streat address 2.
	 *
	 * @return the streat address 2
	 */
	@Column(name = "streat_address2", nullable = false, length = 100)
	public String getStreatAddress2() {
		return this.streatAddress2;
	}

	/**
	 * Sets the streat address 2.
	 *
	 * @param streatAddress2 the new streat address 2
	 */
	public void setStreatAddress2(String streatAddress2) {
		this.streatAddress2 = streatAddress2;
	}

	/**
	 * Gets the suburb.
	 *
	 * @return the suburb
	 */
	@Column(name = "suburb", nullable = false, length = 50)
	public String getSuburb() {
		return this.suburb;
	}

	/**
	 * Sets the suburb.
	 *
	 * @param suburb the new suburb
	 */
	public void setSuburb(String suburb) {
		this.suburb = suburb;
	}

	/**
	 * Gets the city.
	 *
	 * @return the city
	 */
	@Column(name = "city", nullable = false, length = 50)
	public String getCity() {
		return this.city;
	}

	/**
	 * Sets the city.
	 *
	 * @param city the new city
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * Gets the state.
	 *
	 * @return the state
	 */
	@Column(name = "state", nullable = false, length = 50)
	public String getState() {
		return this.state;
	}

	/**
	 * Sets the state.
	 *
	 * @param state the new state
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * Gets the created on.
	 *
	 * @return the created on
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	/**
	 * Sets the created on.
	 *
	 * @param createdOn the new created on
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	/**
	 * Gets the created by.
	 *
	 * @return the created by
	 */
	@Column(name = "created_by", nullable = false, length = 80)
	public String getCreatedBy() {
		return this.createdBy;
	}

	/**
	 * Sets the created by.
	 *
	 * @param createdBy the new created by
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * @return the customerAddressTypeId
	 */
	/**
	 * Gets the customer address type master.
	 *
	 * @return the customer address type master
	 */
	@Column(name = "customer_address_type_id")
	public Long getCustomerAddressTypeId() {
		return customerAddressTypeId;
	}

	/**
	 * @param customerAddressTypeId the customerAddressTypeId to set
	 */
	public void setCustomerAddressTypeId(Long customerAddressTypeId) {
		this.customerAddressTypeId = customerAddressTypeId;
	}

}
