package com.msr.oms.entity;
// Generated Jul 11, 2019 5:20:20 PM by Hibernate Tools 5.1.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerTypeMaster generated by hbm2java.
 */
@Entity
@Table(name = "customer_type_master")
public class CustomerTypeMaster implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = -1327543442201276789L;
	
	/** The customer type id. */
	private Long customerTypeId;
	
	/** The customer type name. */
	private String customerTypeName;
	
	/** The status. */
	private boolean status;
	
	/** The created on. */
	private Date createdOn;
	
	/** The created by. */
	private String createdBy;
	
	/**
	 * Gets the customer type id.
	 *
	 * @return the customer type id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "customer_type_id", unique = true, nullable = false)
	public Long getCustomerTypeId() {
		return this.customerTypeId;
	}

	/**
	 * Sets the customer type id.
	 *
	 * @param customerTypeId the new customer type id
	 */
	public void setCustomerTypeId(Long customerTypeId) {
		this.customerTypeId = customerTypeId;
	}

	/**
	 * Gets the customer type name.
	 *
	 * @return the customer type name
	 */
	@Column(name = "customer_type_name", nullable = false, length = 80)
	public String getCustomerTypeName() {
		return this.customerTypeName;
	}

	/**
	 * Sets the customer type name.
	 *
	 * @param customerTypeName the new customer type name
	 */
	public void setCustomerTypeName(String customerTypeName) {
		this.customerTypeName = customerTypeName;
	}

	/**
	 * Checks if is status.
	 *
	 * @return true, if is status
	 */
	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	/**
	 * Sets the status.
	 *
	 * @param status the new status
	 */
	public void setStatus(boolean status) {
		this.status = status;
	}

	/**
	 * Gets the created on.
	 *
	 * @return the created on
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	/**
	 * Sets the created on.
	 *
	 * @param createdOn the new created on
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	/**
	 * Gets the created by.
	 *
	 * @return the created by
	 */
	@Column(name = "created_by", nullable = false, length = 80)
	public String getCreatedBy() {
		return this.createdBy;
	}

	/**
	 * Sets the created by.
	 *
	 * @param createdBy the new created by
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
}
