package com.msr.oms.entity;
// Generated Jul 11, 2019 5:20:20 PM by Hibernate Tools 5.1.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * EmailSettings generated by hbm2java.
 */
@Entity
@Table(name = "email_settings", uniqueConstraints = @UniqueConstraint(columnNames = "alert_type"))
public class EmailSettings implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 6690746111188175016L;
	
	/** The email sttting id. */
	private Long emailSettingId;
	
	/** The alert type. */
	private String alertType;
	
	/** The email body. */
	private String emailBody;
	
	/** The from email. */
	private String fromEmail;
	
	/** The send type. */
	private String sendType;
	
	/** The signature. */
	private String signature;
	
	/** The status. */
	private Boolean status;
	
	/** The subject. */
	private String subject;
	
	/** The cc mail id. */
	private String ccMailId;
	
	/** The from mail id. */
	private String fromMailId;
	
	/** The send to. */
	private String sendTo;
	
	/** The created by. */
	private String createdBy;
	
	/** The created on. */
	private Date createdOn;

	/**
	 * Instantiates a new email settings.
	 */
	public EmailSettings() {
	}

	/**
	 * Instantiates a new email settings.
	 *
	 * @param alertType the alert type
	 */
	public EmailSettings(String alertType) {
		this.alertType = alertType;
	}

	/**
	 * Gets the email sttting id.
	 *
	 * @return the email sttting id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "email_setting_id", unique = true, nullable = false)
	public Long getEmailSettingId() {
		return this.emailSettingId;
	}

	/**
	 * Sets the email sttting id.
	 *
	 * @param emailStttingId the new email sttting id
	 */
	public void setEmailSettingId(Long emailSettingId) {
		this.emailSettingId = emailSettingId;
	}

	/**
	 * Gets the alert type.
	 *
	 * @return the alert type
	 */
	@Column(name = "alert_type", unique = true, nullable = false)
	public String getAlertType() {
		return this.alertType;
	}

	/**
	 * Sets the alert type.
	 *
	 * @param alertType the new alert type
	 */
	public void setAlertType(String alertType) {
		this.alertType = alertType;
	}

	/**
	 * Gets the email body.
	 *
	 * @return the email body
	 */
	@Column(name = "email_body",columnDefinition="LONGTEXT")
	public String getEmailBody() {
		return this.emailBody;
	}

	/**
	 * Sets the email body.
	 *
	 * @param emailBody the new email body
	 */
	public void setEmailBody(String emailBody) {
		this.emailBody = emailBody;
	}

	/**
	 * Gets the from email.
	 *
	 * @return the from email
	 */
	@Column(name = "from_email")
	public String getFromEmail() {
		return this.fromEmail;
	}

	/**
	 * Sets the from email.
	 *
	 * @param fromEmail the new from email
	 */
	public void setFromEmail(String fromEmail) {
		this.fromEmail = fromEmail;
	}

	/**
	 * Gets the send type.
	 *
	 * @return the send type
	 */
	@Column(name = "send_type")
	public String getSendType() {
		return this.sendType;
	}

	/**
	 * Sets the send type.
	 *
	 * @param sendType the new send type
	 */
	public void setSendType(String sendType) {
		this.sendType = sendType;
	}

	/**
	 * Gets the signature.
	 *
	 * @return the signature
	 */
	@Column(name = "signature",columnDefinition="LONGTEXT")
	public String getSignature() {
		return this.signature;
	}

	/**
	 * Sets the signature.
	 *
	 * @param signature the new signature
	 */
	public void setSignature(String signature) {
		this.signature = signature;
	}

	/**
	 * Gets the status.
	 *
	 * @return the status
	 */
	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	/**
	 * Sets the status.
	 *
	 * @param status the new status
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}

	/**
	 * Gets the subject.
	 *
	 * @return the subject
	 */
	@Column(name = "subject")
	public String getSubject() {
		return this.subject;
	}

	/**
	 * Sets the subject.
	 *
	 * @param subject the new subject
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}

	/**
	 * Gets the cc mail id.
	 *
	 * @return the cc mail id
	 */
	@Column(name = "cc_mail_id")
	public String getCcMailId() {
		return this.ccMailId;
	}

	/**
	 * Sets the cc mail id.
	 *
	 * @param ccMailId the new cc mail id
	 */
	public void setCcMailId(String ccMailId) {
		this.ccMailId = ccMailId;
	}

	/**
	 * Gets the from mail id.
	 *
	 * @return the from mail id
	 */
	@Column(name = "from_mail_id")
	public String getFromMailId() {
		return this.fromMailId;
	}

	/**
	 * Sets the from mail id.
	 *
	 * @param fromMailId the new from mail id
	 */
	public void setFromMailId(String fromMailId) {
		this.fromMailId = fromMailId;
	}

	/**
	 * Gets the send to.
	 *
	 * @return the send to
	 */
	@Column(name = "send_to")
	public String getSendTo() {
		return this.sendTo;
	}

	/**
	 * Sets the send to.
	 *
	 * @param sendTo the new send to
	 */
	public void setSendTo(String sendTo) {
		this.sendTo = sendTo;
	}

	/**
	 * Gets the created by.
	 *
	 * @return the created by
	 */
	@Column(name = "created_by", length = 80)
	public String getCreatedBy() {
		return this.createdBy;
	}

	/**
	 * Sets the created by.
	 *
	 * @param createdBy the new created by
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * Gets the created on.
	 *
	 * @return the created on
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	/**
	 * Sets the created on.
	 *
	 * @param createdOn the new created on
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

}
