package com.msr.oms.entity;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// TODO: Auto-generated Javadoc
/**
 * Customer generated by hbm2java.
 */
@Entity
@Table(name = "influencer")
public class InfluencerEntity implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = -7163677773020271169L;
	
	/** The customer id. */
	private Long influencerId;
	
	/** The customer name. */
	private String customerName;
	
	/** The company code. */
	private String companyCode;
	
	/** The phone number. */
	private Long companyPhoneNumber;
	
	/** The tax. */
	private String tax;
	
	/** The fax no. */
	private String faxNo;
	
	/** The company website. */
	private String companyWebsite;
	
	/** The email id. */
	private String companyEmail;
	
	/** The tags. */
	private String tags;
	
	/** The description. */
	private String description;
	
	/** The address name. */
	private String addressName;
	
	/** The address line 1. */
	private String addressLine1;
	
	/** The address line 2. */
	private String	addressLine2;
	
	
	/** The suburb. */
	private String suburb;
	
	/** The city. */
	private String city;
	
	/** The state. */
	private String state;
	
	/** The zipcode. */
	private Integer zipcode;
	
	/** The address email. */
	private String addressEmail;
	
    /** The address phone number. */
    private Long	addressPhoneNumber;
	
	/** The status. */
	private boolean status;
	
	/** The created on. */
	private Date createdOn;
	
	/** The created by. */
	private String createdBy;
	
	/** The term. */
	private boolean term;

	/** The billing shipping flag. */
	private boolean billingShippingFlag;

	/**
	 * Checks if is term.
	 *
	 * @return the term
	 */
	@Column(name = "term")
	public boolean isTerm() {
		return term;
	}

	/**
	 * Checks if is billing shipping flag.
	 *
	 * @return the billingShippingFlag
	 */
	@Column(name = "billing_shipping_flag")
	public boolean isBillingShippingFlag() {
		return billingShippingFlag;
	}

	/**
	 * Sets the term.
	 *
	 * @param term the term to set
	 */
	public void setTerm(boolean term) {
		this.term = term;
	}

	/**
	 * Sets the billing shipping flag.
	 *
	 * @param billingShippingFlag the billingShippingFlag to set
	 */
	public void setBillingShippingFlag(boolean billingShippingFlag) {
		this.billingShippingFlag = billingShippingFlag;
	}
	
	/**
	 * Gets the influencer id.
	 *
	 * @return the influencerId
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "influencer_id", unique = true, nullable = false)
	public Long getInfluencerId() {
		return influencerId;
	}

	/**
	 * Sets the influencer id.
	 *
	 * @param influencerId the influencerId to set
	 */
	public void setInfluencerId(Long influencerId) {
		this.influencerId = influencerId;
	}

	/**
	 * Gets the customer type master.
	 *
	 * @return the customer type master
	 */

	/**
	 * Gets the customer name.
	 *
	 * @return the customer name
	 */
	@Column(name = "customer_name", nullable = false, length = 80)
	public String getCustomerName() {
		return this.customerName;
	}

	/**
	 * Sets the customer name.
	 *
	 * @param customerName the new customer name
	 */
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}
	
	/**
	 * Checks if is status.
	 *
	 * @return true, if is status
	 */
	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	/**
	 * Sets the status.
	 *
	 * @param status the new status
	 */
	public void setStatus(boolean status) {
		this.status = status;
	}

	/**
	 * Gets the created on.
	 *
	 * @return the created on
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	/**
	 * Sets the created on.
	 *
	 * @param createdOn the new created on
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	/**
	 * Gets the created by.
	 *
	 * @return the created by
	 */
	@Column(name = "created_by",length = 80)
	public String getCreatedBy() {
		return this.createdBy;
	}

	/**
	 * Sets the created by.
	 *
	 * @param createdBy the new created by
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * Gets the company code.
	 *
	 * @return the company code
	 */
	@Column(name = "company_code")
	public String getCompanyCode() {
		return companyCode;
	}

	/**
	 * Sets the company code.
	 *
	 * @param companyCode the new company code
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	/**
	 * Gets the tax.
	 *
	 * @return the tax
	 */
	@Column(name = "tax")
	public String getTax() {
		return tax;
	}

	/**
	 * Sets the tax.
	 *
	 * @param tax the new tax
	 */
	public void setTax(String tax) {
		this.tax = tax;
	}

	/**
	 * Gets the fax no.
	 *
	 * @return the fax no
	 */
	@Column(name = "fax_no")
	public String getFaxNo() {
		return faxNo;
	}

	/**
	 * Sets the fax no.
	 *
	 * @param faxNo the new fax no
	 */
	public void setFaxNo(String faxNo) {
		this.faxNo = faxNo;
	}

	/**
	 * Gets the company website.
	 *
	 * @return the company website
	 */
	@Column(name = "company_website")
	public String getCompanyWebsite() {
		return companyWebsite;
	}

	/**
	 * Sets the company website.
	 *
	 * @param companyWebsite the new company website
	 */
	public void setCompanyWebsite(String companyWebsite) {
		this.companyWebsite = companyWebsite;
	}

	/**
	 * Gets the tags.
	 *
	 * @return the tags
	 */
	@Column(name = "tags")
	public String getTags() {
		return tags;
	}

	/**
	 * Sets the tags.
	 *
	 * @param tags the new tags
	 */
	public void setTags(String tags) {
		this.tags = tags;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	@Column(name = "description")
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Gets the company phone number.
	 *
	 * @return the company phone number
	 */
	@Column(name = "company_phone_number")
	public Long getCompanyPhoneNumber() {
		return companyPhoneNumber;
	}

	/**
	 * Sets the company phone number.
	 *
	 * @param companyPhoneNumber the new company phone number
	 */
	public void setCompanyPhoneNumber(Long companyPhoneNumber) {
		this.companyPhoneNumber = companyPhoneNumber;
	}

	/**
	 * Gets the company email.
	 *
	 * @return the company email
	 */
	@Column(name = "company_email")
	public String getCompanyEmail() {
		return companyEmail;
	}

	/**
	 * Sets the company email.
	 *
	 * @param companyEmail the new company email
	 */
	public void setCompanyEmail(String companyEmail) {
		this.companyEmail = companyEmail;
	}

	/**
	 * Gets the address name.
	 *
	 * @return the address name
	 */
	@Column(name = "address_name")
	public String getAddressName() {
		return addressName;
	}

	/**
	 * Sets the address name.
	 *
	 * @param addressName the new address name
	 */
	public void setAddressName(String addressName) {
		this.addressName = addressName;
	}

	/**
	 * Gets the address line 1.
	 *
	 * @return the address line 1
	 */
	@Column(name = "address_line_1")
	public String getAddressLine1() {
		return addressLine1;
	}

	/**
	 * Sets the address line 1.
	 *
	 * @param addressLine1 the new address line 1
	 */
	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	/**
	 * Gets the address line 2.
	 *
	 * @return the address line 2
	 */
	@Column(name = "address_line_2")
	public String getAddressLine2() {
		return addressLine2;
	}

	/**
	 * Sets the address line 2.
	 *
	 * @param addressLine2 the new address line 2
	 */
	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	/**
	 * Gets the suburb.
	 *
	 * @return the suburb
	 */
	@Column(name = "suburb")
	public String getSuburb() {
		return suburb;
	}

	/**
	 * Sets the suburb.
	 *
	 * @param suburb the new suburb
	 */
	public void setSuburb(String suburb) {
		this.suburb = suburb;
	}

	/**
	 * Gets the city.
	 *
	 * @return the city
	 */
	@Column(name = "city")
	public String getCity() {
		return city;
	}

	/**
	 * Sets the city.
	 *
	 * @param city the new city
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * Gets the state.
	 *
	 * @return the state
	 */
	@Column(name = "state")
	public String getState() {
		return state;
	}

	/**
	 * Sets the state.
	 *
	 * @param state the new state
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * Gets the zipcode.
	 *
	 * @return the zipcode
	 */
	@Column(name = "zipcode")
	public Integer getZipcode() {
		return zipcode;
	}

	/**
	 * Sets the zipcode.
	 *
	 * @param zipcode the new zipcode
	 */
	public void setZipcode(Integer zipcode) {
		this.zipcode = zipcode;
	}

	/**
	 * Gets the address email.
	 *
	 * @return the address email
	 */
	@Column(name = "address_email")
	public String getAddressEmail() {
		return addressEmail;
	}

	/**
	 * Sets the address email.
	 *
	 * @param addressEmail the new address email
	 */
	public void setAddressEmail(String addressEmail) {
		this.addressEmail = addressEmail;
	}

	/**
	 * Gets the address phone number.
	 *
	 * @return the address phone number
	 */
	@Column(name = "address_phone_number")
	public Long getAddressPhoneNumber() {
		return addressPhoneNumber;
	}

	/**
	 * Sets the address phone number.
	 *
	 * @param addressPhoneNumber the new address phone number
	 */
	public void setAddressPhoneNumber(Long addressPhoneNumber) {
		this.addressPhoneNumber = addressPhoneNumber;
	}
}
