package com.msr.oms.entity;
// Generated Jul 11, 2019 5:20:20 PM by Hibernate Tools 5.1.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.msr.product.entity.ColorsMaster;
import com.msr.product.entity.Product;
import com.msr.product.entity.SizeMaster;
import com.msr.product.entity.StylesMaster;

// TODO: Auto-generated Javadoc
/**
 * OrderItems generated by hbm2java.
 */
@Entity
@Table(name = "order_items")
public class OrderItems implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = -53426049334171701L;

	/** The order item id. */
	private Long orderItemId;

	/** The orders. */
	private Orders orders;

	private Product product;

	/** The item name. */
	private String itemName;

	/** The order quantity. */
	private String orderQuantity;

	/** The price. */
	private String price;

	/** The discount. */
	private String discount;

	/** The tax. */
	private String tax;

	/** The total. */
	private String total;

	/** The style master. */
	private StylesMaster styleMaster;

	/** The colors master. */
	private ColorsMaster colorsMaster;

	/** The size master. */
	private SizeMaster sizeMaster;
	/** The status. */
	private boolean status;

	/** The created on. */
	private Date createdOn;

	/** The created by. */
	private String createdBy;

	/**
	 * Gets the order item id.
	 *
	 * @return the order item id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_item_id", unique = true, nullable = false)
	public Long getOrderItemId() {
		return this.orderItemId;
	}

	/**
	 * Sets the order item id.
	 *
	 * @param orderItemId
	 *            the new order item id
	 */
	public void setOrderItemId(Long orderItemId) {
		this.orderItemId = orderItemId;
	}

	/**
	 * Gets the orders.
	 *
	 * @return the orders
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "order_id", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	/**
	 * Sets the orders.
	 *
	 * @param orders
	 *            the new orders
	 */
	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	/**
	 * Gets the order quantity.
	 *
	 * @return the order quantity
	 */
	@Column(name = "order_quantity", nullable = false, length = 50)
	public String getOrderQuantity() {
		return this.orderQuantity;
	}

	/**
	 * Sets the order quantity.
	 *
	 * @param orderQuantity
	 *            the new order quantity
	 */
	public void setOrderQuantity(String orderQuantity) {
		this.orderQuantity = orderQuantity;
	}

	/**
	 * Gets the price.
	 *
	 * @return the price
	 */
	@Column(name = "price", nullable = false, length = 50)
	public String getPrice() {
		return this.price;
	}

	/**
	 * Sets the price.
	 *
	 * @param price
	 *            the new price
	 */
	public void setPrice(String price) {
		this.price = price;
	}

	/**
	 * Gets the discount.
	 *
	 * @return the discount
	 */
	@Column(name = "discount", length = 50)
	public String getDiscount() {
		return this.discount;
	}

	/**
	 * Sets the discount.
	 *
	 * @param discount
	 *            the new discount
	 */
	public void setDiscount(String discount) {
		this.discount = discount;
	}

	/**
	 * Gets the tax.
	 *
	 * @return the tax
	 */
	@Column(name = "tax", length = 50)
	public String getTax() {
		return this.tax;
	}

	/**
	 * Sets the tax.
	 *
	 * @param tax
	 *            the new tax
	 */
	public void setTax(String tax) {
		this.tax = tax;
	}

	/**
	 * Gets the total.
	 *
	 * @return the total
	 */
	@Column(name = "total", length = 50)
	public String getTotal() {
		return this.total;
	}

	/**
	 * Sets the total.
	 *
	 * @param total
	 *            the new total
	 */
	public void setTotal(String total) {
		this.total = total;
	}

	/**
	 * Checks if is status.
	 *
	 * @return true, if is status
	 */
	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	/**
	 * Sets the status.
	 *
	 * @param status
	 *            the new status
	 */
	public void setStatus(boolean status) {
		this.status = status;
	}

	/**
	 * Gets the created on.
	 *
	 * @return the created on
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	/**
	 * Sets the created on.
	 *
	 * @param createdOn
	 *            the new created on
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	/**
	 * Gets the created by.
	 *
	 * @return the created by
	 */
	@Column(name = "created_by", length = 80)
	public String getCreatedBy() {
		return this.createdBy;
	}

	/**
	 * Sets the created by.
	 *
	 * @param createdBy
	 *            the new created by
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * Gets the serialversionuid.
	 *
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
	 * Gets the item name.
	 *
	 * @return the item name
	 */
	@Column(name = "item_name", nullable = false, length = 80)
	public String getItemName() {
		return itemName;
	}

	/**
	 * Sets the item name.
	 *
	 * @param itemName
	 *            the new item name
	 */
	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	/**
	 * @return the product
	 */
	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return product;
	}

	/**
	 * @param product
	 *            the product to set
	 */
	public void setProduct(Product product) {
		this.product = product;
	}

	/**
	 * @return the styleMaster
	 */
	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "style_id")
	public StylesMaster getStyleMaster() {
		return styleMaster;
	}

	/**
	 * @param styleMaster
	 *            the styleMaster to set
	 */
	public void setStyleMaster(StylesMaster styleMaster) {
		this.styleMaster = styleMaster;
	}

	/**
	 * @return the colorsMaster
	 */
	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "color_id")
	public ColorsMaster getColorsMaster() {
		return colorsMaster;
	}

	/**
	 * @param colorsMaster
	 *            the colorsMaster to set
	 */
	public void setColorsMaster(ColorsMaster colorsMaster) {
		this.colorsMaster = colorsMaster;
	}

	/**
	 * @return the sizeMaster
	 */
	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "size_id")
	public SizeMaster getSizeMaster() {
		return sizeMaster;
	}

	/**
	 * @param sizeMaster
	 *            the sizeMaster to set
	 */
	public void setSizeMaster(SizeMaster sizeMaster) {
		this.sizeMaster = sizeMaster;
	}
}
