package com.msr.oms.entity;
// Generated Jul 11, 2019 5:20:20 PM by Hibernate Tools 5.1.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// TODO: Auto-generated Javadoc
/**
 * Orders generated by hbm2java.
 */
@Entity
@Table(name = "orders")
public class Orders implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = -8837186667754696011L;
	
	/** The order id. */
	private Long orderId;
	
	/** The currency master. */
	private CurrencyMaster currencyMaster;
	
	/** The order assign. */
	private OrderAssign orderAssign;
	
	/** The customer. */
	private Customer customer;
	
	/** The price list master. */
	private PriceListMaster priceListMaster;
	
	/** The shipping cost master. */
	private ShippingCostMaster shippingCostMaster;
	
	/** The total are master. */
	private TotalAreMaster totalAreMaster;
	
	/** The manufacturers. */
	private Manufacturers manufacturers;
	
	/** The sale order id. */
	private String saleOrderId;
	
	/** The issue date. */
	private String issueDate;
	
	/** The shipment date. */
	private String shipmentDate;
	
	/** The references. */
	private String references;
	
	/** The email. */
	private String email;
	
	/** The phone. */
	private String phone;
	
	/** The coupon. */
	private String coupon;
	
	/** The message to customer. */
	private String messageToCustomer;
	
	/** The total units. */
	private Integer totalUnits;
	
	/** The sub total. */
	private Integer subTotal;
	
	/** The total cost. */
	private Integer totalCost;
	
	/** The total discount. */
	private String totalDiscount;
	
	/** The cloned parent id. */
	private String clonedParentId;
	
	/** The status. */
	private boolean status;
	
	/** The order status. */
	private String orderStatus;
	
	/** The created on. */
	private Date createdOn;
	
	/** The created by. */
	private String createdBy;
	
	/** The created on. */
	private Date updatedOn;
	
	/** The created by. */
	private String updatedBy;
	
	/** The total tax. */
	private BigDecimal totalTax;
	
	/** The order itemses. */
	private Set<OrderItems> orderItemses = new HashSet<OrderItems>(0);
	 
	private String paymentStatus;


	@Column(name = "payments_status")
	public String getPaymentStatus() {
		return paymentStatus;
	}

	public void setPaymentStatus(String paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	/**
	 * Gets the order id.
	 *
	 * @return the order id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_id", unique = true )
	public Long getOrderId() {
		return this.orderId;
	}

	/**
	 * Sets the order id.
	 *
	 * @param orderId the new order id
	 */
	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	/**
	 * Gets the currency master.
	 *
	 * @return the currency master
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "currency_id" )
	public CurrencyMaster getCurrencyMaster() {
		return this.currencyMaster;
	}

	/**
	 * Sets the currency master.
	 *
	 * @param currencyMaster the new currency master
	 */
	public void setCurrencyMaster(CurrencyMaster currencyMaster) {
		this.currencyMaster = currencyMaster;
	}

	/**
	 * Gets the customer.
	 *
	 * @return the customer
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customer_id" )
	public Customer getCustomer() {
		return this.customer;
	}

	/**
	 * Sets the customer.
	 *
	 * @param customer the new customer
	 */
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	/**
	 * Gets the price list master.
	 *
	 * @return the price list master
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "price_list_id" )
	public PriceListMaster getPriceListMaster() {
		return this.priceListMaster;
	}

	/**
	 * Sets the price list master.
	 *
	 * @param priceListMaster the new price list master
	 */
	public void setPriceListMaster(PriceListMaster priceListMaster) {
		this.priceListMaster = priceListMaster;
	}

	/**
	 * Gets the shipping cost master.
	 *
	 * @return the shipping cost master
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "shippling_cost_id")
	public ShippingCostMaster getShippingCostMaster() {
		return this.shippingCostMaster;
	}

	/**
	 * Sets the shipping cost master.
	 *
	 * @param shippingCostMaster the new shipping cost master
	 */
	public void setShippingCostMaster(ShippingCostMaster shippingCostMaster) {
		this.shippingCostMaster = shippingCostMaster;
	}

	/**
	 * Gets the total are master.
	 *
	 * @return the total are master
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "total_are_id" )
	public TotalAreMaster getTotalAreMaster() {
		return this.totalAreMaster;
	}

	/**
	 * Sets the total are master.
	 *
	 * @param totalAreMaster the new total are master
	 */
	public void setTotalAreMaster(TotalAreMaster totalAreMaster) {
		this.totalAreMaster = totalAreMaster;
	}
	
	/**
	 * Gets the manufacturers.
	 *
	 * @return the manufacturers
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "manufacturer_id" )
	public Manufacturers getManufacturers() {
		return manufacturers;
	}

	/**
	 * Sets the manufacturers.
	 *
	 * @param manufacturers the new manufacturers
	 */
	public void setManufacturers(Manufacturers manufacturers) {
		this.manufacturers = manufacturers;
	}


	/**
	 * Gets the sale order id.
	 *
	 * @return the sale order id
	 */
	@Column(name = "sale_order_id" , length = 20)
	public String getSaleOrderId() {
		return this.saleOrderId;
	}

	/**
	 * Sets the sale order id.
	 *
	 * @param saleOrderId the new sale order id
	 */
	public void setSaleOrderId(String saleOrderId) {
		this.saleOrderId = saleOrderId;
	}

	/**
	 * Gets the issue date.
	 *
	 * @return the issue date
	 */
	@Column(name = "issue_date" , length = 15)
	public String getIssueDate() {
		return this.issueDate;
	}

	/**
	 * Sets the issue date.
	 *
	 * @param issueDate the new issue date
	 */
	public void setIssueDate(String issueDate) {
		this.issueDate = issueDate;
	}

	/**
	 * Gets the shipment date.
	 *
	 * @return the shipment date
	 */
	@Column(name = "shipment_date" , length = 15)
	public String getShipmentDate() {
		return this.shipmentDate;
	}

	/**
	 * Sets the shipment date.
	 *
	 * @param shipmentDate the new shipment date
	 */
	public void setShipmentDate(String shipmentDate) {
		this.shipmentDate = shipmentDate;
	}

	/**
	 * Gets the references.
	 *
	 * @return the references
	 */
	@Column(name = "references_data" , length = 50)
	public String getReferences() {
		return this.references;
	}

	/**
	 * Sets the references.
	 *
	 * @param references the new references
	 */
	public void setReferences(String references) {
		this.references = references;
	}

	/**
	 * Gets the email.
	 *
	 * @return the email
	 */
	@Column(name = "email" , length = 30)
	public String getEmail() {
		return this.email;
	}

	/**
	 * Sets the email.
	 *
	 * @param email the new email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Gets the phone.
	 *
	 * @return the phone
	 */
	@Column(name = "phone" , length = 15)
	public String getPhone() {
		return this.phone;
	}

	/**
	 * Sets the phone.
	 *
	 * @param phone the new phone
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * Gets the coupon.
	 *
	 * @return the coupon
	 */
	@Column(name = "coupon" , length = 30)
	public String getCoupon() {
		return this.coupon;
	}

	/**
	 * Sets the coupon.
	 *
	 * @param coupon the new coupon
	 */
	public void setCoupon(String coupon) {
		this.coupon = coupon;
	}

	/**
	 * Gets the message to customer.
	 *
	 * @return the message to customer
	 */
	@Column(name = "message_to_customer" , length = 150)
	public String getMessageToCustomer() {
		return this.messageToCustomer;
	}

	/**
	 * Sets the message to customer.
	 *
	 * @param messageToCustomer the new message to customer
	 */
	public void setMessageToCustomer(String messageToCustomer) {
		this.messageToCustomer = messageToCustomer;
	}

	/**
	 * Gets the total units.
	 *
	 * @return the total units
	 */
	@Column(name = "total_units" , length = 20)
	public Integer getTotalUnits() {
		return this.totalUnits;
	}

	/**
	 * Sets the total units.
	 *
	 * @param totalUnits the new total units
	 */
	public void setTotalUnits(Integer totalUnits) {
		this.totalUnits = totalUnits;
	}

	/**
	 * Gets the sub total.
	 *
	 * @return the sub total
	 */
	@Column(name = "sub_total" , length = 20)
	public Integer getSubTotal() {
		return this.subTotal;
	}

	/**
	 * Sets the sub total.
	 *
	 * @param subTotal the new sub total
	 */
	public void setSubTotal(Integer subTotal) {
		this.subTotal = subTotal;
	}

	/**
	 * Gets the total cost.
	 *
	 * @return the total cost
	 */
	@Column(name = "total_cost" , length = 20)
	public Integer getTotalCost() {
		return this.totalCost;
	}

	/**
	 * Sets the total cost.
	 *
	 * @param totalCost the new total cost
	 */
	public void setTotalCost(Integer totalCost) {
		this.totalCost = totalCost;
	}

	/**
	 * Gets the cloned parent id.
	 *
	 * @return the cloned parent id
	 */
	@Column(name = "cloned_parent_id" , length = 20)
	public String getClonedParentId() {
		return this.clonedParentId;
	}

	/**
	 * Sets the cloned parent id.
	 *
	 * @param clonedParentId the new cloned parent id
	 */
	public void setClonedParentId(String clonedParentId) {
		this.clonedParentId = clonedParentId;
	}

	/**
	 * Checks if is status.
	 *
	 * @return true, if is status
	 */
	@Column(name = "status" )
	public boolean isStatus() {
		return this.status;
	}

	/**
	 * Sets the status.
	 *
	 * @param status the new status
	 */
	public void setStatus(boolean status) {
		this.status = status;
	}

	/**
	 * Gets the order status.
	 *
	 * @return the order status
	 */
	@Column(name = "order_status" , length = 5)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	/**
	 * Sets the order status.
	 *
	 * @param orderStatus the new order status
	 */
	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	/**
	 * Gets the created on.
	 *
	 * @return the created on
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on")
	public Date getCreatedOn() {
		return this.createdOn;
	}

	/**
	 * Sets the created on.
	 *
	 * @param createdOn the new created on
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	/**
	 * Gets the created by.
	 *
	 * @return the created by
	 */
	@Column(name = "created_by" , length = 80)
	public String getCreatedBy() {
		return this.createdBy;
	}

	/**
	 * Sets the created by.
	 *
	 * @param createdBy the new created by
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * Gets the order itemses.
	 *
	 * @return the order itemses
	 */
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "orders")
	public Set<OrderItems> getOrderItemses() {
		return this.orderItemses;
	}

	/**
	 * Sets the order itemses.
	 *
	 * @param orderItemses the new order itemses
	 */
	public void setOrderItemses(Set<OrderItems> orderItemses) {
		this.orderItemses = orderItemses;
	}

	
	/**
	 * Gets the order assign.
	 *
	 * @return the order assign
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "order_assign_to_id" )
	public OrderAssign getOrderAssign() {
		return orderAssign;
	}

	/**
	 * Sets the order assign.
	 *
	 * @param orderAssign the new order assign
	 */
	public void setOrderAssign(OrderAssign orderAssign) {
		this.orderAssign = orderAssign;
	}

	/**
	 * Gets the updated on.
	 *
	 * @return the updatedOn
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on")
	public Date getUpdatedOn() {
		return updatedOn;
	}

	/**
	 * Sets the updated on.
	 *
	 * @param updatedOn the updatedOn to set
	 */
	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	/**
	 * Gets the updated by.
	 *
	 * @return the updatedBy
	 */
	@Column(name = "updated_by")
	public String getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * Sets the updated by.
	 *
	 * @param updatedBy the updatedBy to set
	 */
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
	 * Gets the total tax.
	 *
	 * @return the totalTax
	 */
	@Column(name = "total_tax")
	public BigDecimal getTotalTax() {
		return totalTax;
	}

	/**
	 * Sets the total tax.
	 *
	 * @param totalTax the totalTax to set
	 */
	public void setTotalTax(BigDecimal totalTax) {
		this.totalTax = totalTax;
	}

	/**
	 * Gets the total discount.
	 *
	 * @return the totalDiscount
	 */
	@Column(name = "total_discount")
	public String getTotalDiscount() {
		return totalDiscount;
	}

	/**
	 * Sets the total discount.
	 *
	 * @param totalDiscount the totalDiscount to set
	 */
	public void setTotalDiscount(String totalDiscount) {
		this.totalDiscount = totalDiscount;
	}
}
