package com.msr.oms.entity;
// Generated Jul 11, 2019 5:20:20 PM by Hibernate Tools 5.1.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TotalAreMaster generated by hbm2java.
 */
@Entity
@Table(name = "total_are_master")
public class TotalAreMaster implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = -1440179286206185017L;
	
	/** The total are id. */
	private Long totalAreId;
	
	/** The total are name. */
	private String totalAreName;
	
	/** The status. */
	private boolean status;
	
	/** The created on. */
	private Date createdOn;
	
	/** The created by. */
	private String createdBy;
	
	/**
	 * Gets the total are id.
	 *
	 * @return the total are id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "total_are_id", unique = true, nullable = false)
	public Long getTotalAreId() {
		return this.totalAreId;
	}

	/**
	 * Sets the total are id.
	 *
	 * @param totalAreId the new total are id
	 */
	public void setTotalAreId(Long totalAreId) {
		this.totalAreId = totalAreId;
	}

	/**
	 * Gets the total are name.
	 *
	 * @return the total are name
	 */
	@Column(name = "total_are_name", nullable = false, length = 50)
	public String getTotalAreName() {
		return this.totalAreName;
	}

	/**
	 * Sets the total are name.
	 *
	 * @param totalAreName the new total are name
	 */
	public void setTotalAreName(String totalAreName) {
		this.totalAreName = totalAreName;
	}

	/**
	 * Checks if is status.
	 *
	 * @return true, if is status
	 */
	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	/**
	 * Sets the status.
	 *
	 * @param status the new status
	 */
	public void setStatus(boolean status) {
		this.status = status;
	}

	/**
	 * Gets the created on.
	 *
	 * @return the created on
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	/**
	 * Sets the created on.
	 *
	 * @param createdOn the new created on
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	/**
	 * Gets the created by.
	 *
	 * @return the created by
	 */
	@Column(name = "created_by",length = 80)
	public String getCreatedBy() {
		return this.createdBy;
	}

	/**
	 * Sets the created by.
	 *
	 * @param createdBy the new created by
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * Gets the orderses.
	 *
	 * @return the orderses
	 */

}
